### ISSUE TITLE
Family naming

### ISSUE THREAD

**Issue by davelab6** [BornaIz/Lalezar#1]
For a single style font, if you think it might become part of a multi-weight family in the future, it is better to append 'One' to the family name, so we avoid a 'Lobster Two' situation. 

If you think this will always be a single weight design, perhaps 'Lalezar-Regular' would be better, and if you do a text version in future, call it 'Lalezar Text'? :)

Please rename the files, perhaps as follows

    git mv Lalezar-Display.otf  LalezarOne-Regular.otf 
    git mv Lalezar-Display.ttf  LalezarOne-Regular.ttf
    git mv OFL_Lalezar.txt OFL.txt

Also please update the family naming internally.

**Comment by BornaIz** [comment]
I just changed it to Lalezar-Regular.

**Comment by davelab6** [comment]
https://github.com/BornaIz/Lalezar/commit/87bca4aa7cc197e06746085fbb925f3a7df4d0d5 removed the OFL instead of renaming it. I'll make a Pull Request to address this.

**Comment by davelab6** [comment]
Fixed in #3
