### ISSUE TITLE
Releasing v1.003 onto GF

### ISSUE THREAD

**Issue by m4rc1e** [BornaIz/Lalezar#10]
Hello,

We've been meaning to release this font for quite some time. I see the last version we have hosted on Google Fonts is v1.000.

Do you mind if I bring it up to scratch with our new [specification](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md)?

I'll also get rid of the v1.002 sources. We should always have just 1 set of sources.

cc @davelab6

**Comment by BornaIz** [comment]
Dear Marc,

Please go ahead with the release and the necessary amendments, and let me
know if I need to do anything.

Best,
Borna

*-*
*Borna Izadpanah*
PhD Researcher
Perso-Arabic typography, printing history & culture
University of Reading
*-*
www.borna.design

**Comment by m4rc1e** [comment]
Thanks
