### ISSUE TITLE
The word 'الله' shown as 'لله'

### ISSUE THREAD

**Issue by xsoh** [BornaIz/Lalezar#8]
Dears, 
Thanks for this awesome font! I really like it.
Just for note when writing the word `Allāh, ﷲ‎ = U+FDF2` it show as 'لله'.

Thanks again.

**Comment by BornaIz** [comment]
Hi, thank you for the kind words.
It should be fixed now. 
Please try the new release (1.003).

**Comment by xsoh** [comment]
works very well 👍 
Thanks!

**Comment by Noon110** [comment]
,
